AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service Deployment for Backend with ALB and Blue/Green Support'

Parameters:
  ServiceName:
    Type: String
    Default: backend
    Description: Name of the service

  ClusterName:
    Type: String
    Default: auto-deploy-prod-cluster
    Description: ECS Cluster name

  ImageUri:
    Type: String
    Description: Docker image URI with tag

  ContainerPort:
    Type: Number
    Default: 8000
    Description: Port the container listens on

  DesiredCount:
    Type: Number
    Default: 2
    Description: Number of tasks to run

  Cpu:
    Type: String
    Default: '512'
    Description: CPU units for the task

  Memory:
    Type: String
    Default: '1024'
    Description: Memory (MB) for the task

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be created

  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-delimited list of subnet IDs for the service

  TaskExecutionRoleArn:
    Type: String
    Description: ARN of ECS task execution role

  TaskRoleArn:
    Type: String
    Description: ARN of ECS task role

  LogGroupName:
    Type: String
    Default: /ecs/auto-deploy-prod
    Description: CloudWatch log group name

  HostedZoneId:
    Type: String
    Default: Z0937327HD133Q6A55PH
    Description: Route53 Hosted Zone ID

  DomainName:
    Type: String
    Default: api.webbyftw.co.in
    Description: Domain name for the service

Resources:
  # ALB Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${ServiceName} ALB'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow HTTPS
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-alb-sg'

  # Application Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-alb'

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-299
      DeregistrationDelay: 30
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-tg'

  # ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # Route53 DNS Record
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt LoadBalancer.DNSName
        EvaluateTargetHealth: true

  # Security Group for ECS Service
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${ServiceName} service'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Allow traffic from ALB
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-service-sg'

  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'auto-deploy-${ServiceName}'
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          Environment:
            - Name: ENVIRONMENT
              Value: production
            - Name: DATABASE_URL
              Value: sqlite:///./employees.db
            - Name: PROJECT_NAME
              Value: Enterprise Employee Management System
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ServiceName
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-task'

  # ECS Service with Blue/Green Deployment
  Service:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets: !Ref SubnetIds
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-service'

Outputs:
  ServiceName:
    Description: Name of the ECS service
    Value: !GetAtt Service.Name

  ServiceArn:
    Description: ARN of the ECS service
    Value: !Ref Service

  TaskDefinitionArn:
    Description: ARN of the task definition
    Value: !Ref TaskDefinition

  LoadBalancerDNS:
    Description: DNS name of the load balancer
    Value: !GetAtt LoadBalancer.DNSName

  LoadBalancerArn:
    Description: ARN of the load balancer
    Value: !Ref LoadBalancer

  TargetGroupArn:
    Description: ARN of the target group
    Value: !Ref TargetGroup

  DomainName:
    Description: Custom domain name
    Value: !Ref DomainName
