AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service Deployment for Backend with ALB and Blue/Green Support'

Parameters:
  ServiceName:
    Type: String
    Default: backend
    Description: Name of the service

  ClusterName:
    Type: String
    Default: auto-deploy-prod-cluster
    Description: ECS Cluster name

  ImageUri:
    Type: String
    Description: Docker image URI with tag

  ContainerPort:
    Type: Number
    Default: 80
    Description: Port the container listens on

  DesiredCount:
    Type: Number
    Default: 2
    Description: Number of tasks to run

  Cpu:
    Type: String
    Default: '512'
    Description: CPU units for the task

  Memory:
    Type: String
    Default: '1024'
    Description: Memory (MB) for the task

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be created

  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-delimited list of subnet IDs for the service

  TaskExecutionRoleArn:
    Type: String
    Description: ARN of ECS task execution role

  TaskRoleArn:
    Type: String
    Description: ARN of ECS task role

  LogGroupName:
    Type: String
    Default: /ecs/auto-deploy-prod
    Description: CloudWatch log group name

  HostedZoneId:
    Type: String
    Default: Z0937327HD133Q6A55PH
    Description: Route53 Hosted Zone ID

  DomainName:
    Type: String
    Default: api.webbyftw.co.in
    Description: Domain name for the service

Resources:
  # EFS File System
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub '${ServiceName}-efs'

  # EFS Security Group
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${ServiceName} EFS'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref ServiceSecurityGroup
          Description: Allow NFS from ECS Service
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-efs-sg'

  # Mount Targets (One per subnet)
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Select [0, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Select [1, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  MountTarget3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Select [2, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  # Security Group for ECS Service - OPEN TO WORLD for Direct Access
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${ServiceName} service'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0
          Description: Allow direct traffic from internet
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-service-sg'

  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'auto-deploy-${ServiceName}'
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      Volumes:
        - Name: db-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref FileSystem
            TransitEncryption: ENABLED
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          MountPoints:
            - SourceVolume: db-volume
              ContainerPath: /app/db_data
          Environment:
            - Name: ENVIRONMENT
              Value: production
            - Name: DATABASE_URL
              Value: sqlite:///./db_data/employees.db
            - Name: PROJECT_NAME
              Value: Enterprise Employee Management System
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ServiceName
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "exit 0"
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-task'

  # ECS Service - NO LoadBalancer
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets: !Ref SubnetIds
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      Tags:
        - Key: Name
          Value: !Sub '${ServiceName}-service'

Outputs:
  ServiceName:
    Description: Name of the ECS service
    Value: !GetAtt Service.Name

  ServiceArn:
    Description: ARN of the ECS service
    Value: !Ref Service

  TaskDefinitionArn:
    Description: ARN of the task definition
    Value: !Ref TaskDefinition

  FileSystemId:
    Description: usage EFS FileSystem ID
    Value: !Ref FileSystem

